Refactor body to a single property that handles the content and content type. Remove unnecessary factories
micronaut-projects/micronaut-email pull request #11
Opened 2022-01-20 17:24 UTC by jameskleeh

2022-01-20 17:56 UTC, sdelamo requested changes
Thanks for the `@EachBean` recommendation. I have moved that here:  https://github.com/micronaut-projects/micronaut-email/pull/4/commits/d8ad9937c12db6b537e6df427a5b8a39ede3f417

I don't think this works. 

You can send an email with HTML and text. An email with only text or an email with only HTML. The most common thing is to do both html and text. 

This PR forces the body to be either HTML or text.

2022-01-20 21:57 UTC, jameskleeh commented
I've updated the PR to add support for text fallback for the clients that support it. It seems that sendgrid and Javamail do not.

2022-01-21 09:28 UTC, sdelamo requested changes
I don't like that with this change `TransactionalEmailSenders` to know details about `Body` implementation. They need to check if it is a `MultiPartBody` for example. I am going to change `Body` api to simplify that.

2022-01-21 09:44 UTC, sdelamo approved these changes

2022-01-21 09:45 UTC, merged