Use the supplied contact name in SesEmailComposer
micronaut-projects/micronaut-email pull request #127
Opened 2022-09-21 20:34 UTC by mvelez-nydig

2022-09-21 21:06 UTC, nmostowich-nydig commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +    void "from field should allow to include the sender name"() {
nit but should say "allow including" rather than "allow to include"

2022-10-03 05:54 UTC, sdelamo requested changes
Please, the base branch of this PR should be 1.4.x. Can you change it?

2022-10-03 05:54 UTC, sdelamo commented on email-amazon-ses/src/main/java/io/micronaut/email/ses/SesEmailComposer.java
> +        if (from.getName() != null && !from.getName().isEmpty()) {
Please use https://docs.micronaut.io/latest/api/io/micronaut/core/util/StringUtils.html#isNotEmpty-java.lang.CharSequence-

2022-10-03 05:54 UTC, sdelamo commented on email-amazon-ses/src/main/java/io/micronaut/email/ses/SesEmailComposer.java
> +    private String sourceFormatter(@NonNull Email email) {
make the method protected to allow override and add javadoc

2022-10-03 05:54 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def from = new Contact("sender@example.com", "John Doe")
```suggestion
        Contact from = new Contact("sender@example.com", "John Doe")
```

2022-10-03 05:54 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def formattedFrom = "${from.getName()} <${from.getEmail()}>"
```suggestion
        String formattedFrom = "${from.getName()} <${from.getEmail()}>"
```

2022-10-03 05:54 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def to = "receiver@example.com"
```suggestion
        String to = "receiver@example.com"
```

2022-10-03 05:54 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def subject = "Apple Music"
```suggestion
        String subject = "Apple Music"
```

2022-10-03 05:54 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def request = sesEmailComposer.compose(email) as SendEmailRequest
```suggestion
        SendEmailRequest request = sesEmailComposer.compose(email) as SendEmailRequest
```

2022-10-03 15:19 UTC, mvelez-nydig commented
> Please, the base branch of this PR should be 1.4.x. Can you change it?

@sdelamo changed the base branch and addressed your comments. Let me know if these look right

2022-10-03 21:00 UTC, closed without merging