Upgrade Jakarta Mail to latest spec and implementation.
micronaut-projects/micronaut-email pull request #233
Opened 2023-06-07 15:05 UTC by wetted

- Upgrade Jakarta mail from 2.0.1 to 2.1.2. This includes changes to the dependency coordinates, which separates api and implementation.
- Add Eclipse Angus dependency, which is the direct successor of JakartaMail implementation.
- Fix links to point to moved Jakarta Mail Specification website, and update docs.

2023-06-07 15:06 UTC, wetted commented
@melix I'm not sure I handled the addition of the implementation dependency correctly, in the catalog and build files. Please check me on this.

2023-06-07 15:38 UTC, sdelamo requested changes
It misses a mention in the what's new or breaking changes about the move to angus

2023-06-07 19:39 UTC, melix approved these changes

2023-06-08 07:57 UTC, sdelamo commented on email-javamail-composer/build.gradle.kts
> +    runtimeOnly(libs.managed.eclipse.angus)
I think we should move this dependency to `testRuntimeOnly` and tell the user in the documentation they have to add the implementation they choose as a runtimeOnly dependency. 

We could say to you java email you have to add: 

implementation("io.micronaut.email:micronaut-email-javamail")
and: 
runtimeOnly(libs.managed.eclipse.angus)

2023-06-08 07:58 UTC, sdelamo requested changes
move   `libs.managed.eclipse.angus` to testRuntimeOnly.

2023-06-08 18:56 UTC, sdelamo approved these changes

2023-06-08 18:56 UTC, merged