Issue 259
micronaut-projects/micronaut-email pull request #263
Opened 2023-07-19 09:44 UTC by sdelamo

2023-07-19 09:47 UTC, sdelamo commented
Specifying a validator: 

```java
@Constraint(validatedBy = AnyRecipientValidator.class)
```

makes the test pass for hibernate-validator but fail for Micronaut Validation.

2023-07-21 08:39 UTC, timyates requested changes

2023-07-21 08:39 UTC, timyates commented on email/src/main/java/io/micronaut/email/validation/AnyRecipientValidator.java
Where's this from?

It says 2017-2021 and since 1.0.0, but I cannot find it previously

2023-07-21 10:42 UTC, sdelamo commented on email/src/main/java/io/micronaut/email/validation/AnyRecipientValidator.java
I updated the copyright notice

2023-07-21 10:57 UTC, sdelamo commented on email/src/main/java/io/micronaut/email/validation/AnyRecipientValidator.java
> + * @since 1.0.0
```suggestion
 * @since 4.0.2
```

2023-07-21 11:00 UTC, sdelamo commented on email/src/main/java/io/micronaut/email/validation/AnyRecipientValidator.java
> + * @since 4.0.2
```suggestion
 * @since 2.0.2
```

2023-07-21 11:00 UTC, timyates approved these changes

2023-07-21 11:21 UTC, merged