Allow more than one Reply-To contact in order to be compliant with the Mail RFC
micronaut-projects/micronaut-email pull request #265
Opened 2023-07-20 14:28 UTC by guillermocalvo

Added support for multiple `replyTo` per `Email` in a backward-compatible way.

Sendgrid does not support multiple 'replyTo' addresses, so we will log a warning.

2023-07-21 08:50 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def from = "sender@example.com"
```suggestion
        String from = "sender@example.com"
```

2023-07-21 08:50 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def to = "receiver@example.com"
```suggestion
        String to = "receiver@example.com"
```

2023-07-21 08:50 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def replyTo1 = "sender.reply.to.one@example.com"
```suggestion
        String replyTo1 = "sender.reply.to.one@example.com"
```

2023-07-21 08:51 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def replyTo2 = "sender.reply.to.two@example.com"
```suggestion
        String replyTo2 = "sender.reply.to.two@example.com"
```

2023-07-21 08:51 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def subject = "Apple Music"
```suggestion
        String subject = "Apple Music"
```

2023-07-21 08:51 UTC, sdelamo commented on email-javamail-composer/src/test/groovy/io/micronaut/email/javamail/composer/DefaultMessageComposerSpec.groovy
> +        def from = "sender@example.com"
```suggestion
        String from = "sender@example.com"
```

2023-07-21 08:51 UTC, sdelamo commented on email-javamail-composer/src/test/groovy/io/micronaut/email/javamail/composer/DefaultMessageComposerSpec.groovy
> +        def to = "receiver@example.com"
```suggestion
        String to = "receiver@example.com"
```

2023-07-21 08:55 UTC, sdelamo commented on email-sendgrid/src/test/groovy/io/micronaut/email/sendgrid/SendgridEmailComposerSpec.groovy
> +        def to = "receiver@example.com"
```suggestion
        String to = "receiver@example.com"
```

2023-07-21 08:56 UTC, sdelamo commented on email-sendgrid/src/test/groovy/io/micronaut/email/sendgrid/SendgridEmailComposerSpec.groovy
> +        def subject = "Apple Music"
```suggestion
        String subject = "Apple Music"
```

2023-07-21 08:56 UTC, sdelamo commented on email-sendgrid/src/test/groovy/io/micronaut/email/sendgrid/SendgridEmailComposerSpec.groovy
> +        def request = sendgridEmailComposer.compose(email)
use type not `def`

2023-07-21 08:56 UTC, sdelamo commented on email-sendgrid/src/test/groovy/io/micronaut/email/sendgrid/SendgridEmailComposerSpec.groovy
> +        def map = new ObjectMapper().readValue(request.body, Map)
use type not `def`

2023-07-21 08:56 UTC, sdelamo commented on email-sendgrid/src/test/groovy/io/micronaut/email/sendgrid/SendgridEmailComposerSpec.groovy
> +        def map = new ObjectMapper().readValue(request.body, Map)
use JsnoMapper not ObjectMapper

2023-07-21 08:57 UTC, sdelamo commented on email/src/main/java/io/micronaut/email/Email.java
> +    @Nullable
misses javadoc

2023-07-21 08:59 UTC, sdelamo commented on email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
> +        def request = sesEmailComposer.compose(email) as SendEmailRequest
use type not `def`

2023-07-21 12:43 UTC, guillermocalvo commented
> @sdelamo 
> what about postmark and mailjet?

Those two weren't even implementing single "replyTo" address support.

I just pushed some changes to make them take "replyTo" into account.

2023-07-26 15:48 UTC, sdelamo requested changes

2023-07-26 15:48 UTC, sdelamo commented on email-mailjet/build.gradle.kts
> +    testImplementation(mn.jackson.databind)
use Micronaut Serde

2023-07-27 09:51 UTC, sdelamo approved these changes

2023-07-27 20:44 UTC, sdelamo commented
@guillermocalvo can you merge master into this PR. thanks. I will merge it after you have resolved the conflicts.

2023-07-28 15:32 UTC, merged