Introduce `Attachment.disposition`
micronaut-projects/micronaut-email pull request #272
Opened 2023-07-27 16:44 UTC by guillermocalvo

Closes #123

2023-07-27 20:41 UTC, sdelamo requested changes

2023-07-27 20:41 UTC, sdelamo commented on email/src/main/java/io/micronaut/email/Attachment.java
>      public Attachment(@NonNull String filename,
annotate the new constructor wit `@since`. Annotate the primary constructor with `@Creator`

2023-07-27 20:44 UTC, sdelamo requested changes

2023-07-27 20:44 UTC, sdelamo commented on email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java
> +        att.setHeader("Content-Type", attachment.getContentType());
is content Type non null?

2023-07-27 20:44 UTC, sdelamo commented on email/src/main/java/io/micronaut/email/Attachment.java
> +    public String getDisposition() {
add `@since`

2023-07-27 20:44 UTC, sdelamo commented on email/src/main/java/io/micronaut/email/Attachment.java
> +    public Attachment(@NonNull String filename,
should we deprecate the old constructor?

2023-07-28 08:27 UTC, guillermocalvo commented on email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java
> +        att.setHeader("Content-Type", attachment.getContentType());
Yes; `contentType` is a required field.

```java
    @NonNull
    @NotBlank
    private final String contentType;
```

2023-07-28 15:33 UTC, sdelamo commented
sorry @guillermocalvo . Can merge master into this?

2023-07-28 15:33 UTC, sdelamo approved these changes

2023-07-31 10:05 UTC, merged